"""remove default in completed field of Task model

Revision ID: db7a427f238f
Revises: 58451a74a0f4
Create Date: 2025-05-29 01:48:21.342931

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "db7a427f238f"
down_revision: Union[str, None] = "58451a74a0f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
